// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class Balance {
  final BigInt pending;
  final BigInt confirmed;
  final BigInt total;

  const Balance({
    required this.pending,
    required this.confirmed,
    required this.total,
  });

  @override
  int get hashCode => pending.hashCode ^ confirmed.hashCode ^ total.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Balance &&
          runtimeType == other.runtimeType &&
          pending == other.pending &&
          confirmed == other.confirmed &&
          total == other.total;
}
