// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../lib.dart';
import 'addresses.dart';
import 'balance.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'send.dart';
import 'transactions.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ArkClient>>
abstract class ArkClient implements RustOpaqueInterface {
  Addresses addresses();

  ArcClientEsploraClientWalletInMemoryDb get inner;

  set inner(ArcClientEsploraClientWalletInMemoryDb inner);

  Future<Balance> balance();

  Future<List<Transaction>> fetchTransactions();

  static Future<ArkClient> init({
    required String nsec,
    required String network,
    required String esplora,
    required String server,
  }) => LibArk.instance.api.crateArkClientArkClientInit(
    nsec: nsec,
    network: network,
    esplora: esplora,
    server: server,
  );

  Future<Txid> sendOffChain({required String address, required BigInt sats});

  Future<Txid> sendOnChain({required String address, required BigInt sats});
}
