// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class ServerInfo {
  final String pk;
  final int vtxoTreeExpiry;
  final int unilateralExitDelay;
  final int boardingExitDelay;
  final PlatformInt64 roundInterval;
  final String network;
  final BigInt dust;
  final String forfeitAddress;
  final String version;
  final BigInt? utxoMinAmount;
  final BigInt? utxoMaxAmount;
  final BigInt? vtxoMinAmount;
  final BigInt? vtxoMaxAmount;

  const ServerInfo({
    required this.pk,
    required this.vtxoTreeExpiry,
    required this.unilateralExitDelay,
    required this.boardingExitDelay,
    required this.roundInterval,
    required this.network,
    required this.dust,
    required this.forfeitAddress,
    required this.version,
    this.utxoMinAmount,
    this.utxoMaxAmount,
    this.vtxoMinAmount,
    this.vtxoMaxAmount,
  });

  @override
  int get hashCode =>
      pk.hashCode ^
      vtxoTreeExpiry.hashCode ^
      unilateralExitDelay.hashCode ^
      boardingExitDelay.hashCode ^
      roundInterval.hashCode ^
      network.hashCode ^
      dust.hashCode ^
      forfeitAddress.hashCode ^
      version.hashCode ^
      utxoMinAmount.hashCode ^
      utxoMaxAmount.hashCode ^
      vtxoMinAmount.hashCode ^
      vtxoMaxAmount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ServerInfo &&
          runtimeType == other.runtimeType &&
          pk == other.pk &&
          vtxoTreeExpiry == other.vtxoTreeExpiry &&
          unilateralExitDelay == other.unilateralExitDelay &&
          boardingExitDelay == other.boardingExitDelay &&
          roundInterval == other.roundInterval &&
          network == other.network &&
          dust == other.dust &&
          forfeitAddress == other.forfeitAddress &&
          version == other.version &&
          utxoMinAmount == other.utxoMinAmount &&
          utxoMaxAmount == other.utxoMaxAmount &&
          vtxoMinAmount == other.vtxoMinAmount &&
          vtxoMaxAmount == other.vtxoMaxAmount;
}
