// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.9.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<OutPoint>>
abstract class OutPoint implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<VtxoInfo>>
abstract class VtxoInfo implements RustOpaqueInterface {
  PlatformInt64 get amount;

  PlatformInt64? get confirmationTime;

  PlatformInt64 get createdAt;

  PlatformInt64 get expiresAt;

  bool get isPreconfirmed;

  bool get isSpent;

  bool get isSwept;

  bool get isUnrolled;

  OutPoint get outpoint;

  String get script;

  set amount(PlatformInt64 amount);

  set confirmationTime(PlatformInt64? confirmationTime);

  set createdAt(PlatformInt64 createdAt);

  set expiresAt(PlatformInt64 expiresAt);

  set isPreconfirmed(bool isPreconfirmed);

  set isSpent(bool isSpent);

  set isSwept(bool isSwept);

  set isUnrolled(bool isUnrolled);

  set outpoint(OutPoint outpoint);

  set script(String script);
}
